version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: foodie-server-dc
    container_name: foodie-node-server-dc
    command: npm run start
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=dev
    networks:
      - app-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: foodie-client-dc
    container_name: foodie-node-client-dc
    command: npm run start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

  redisdb:
    image: "redis:alpine"
    restart: always
    hostname: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
